
[
    {
        "id": 1,
        "app_name": "SummarizePro",
        "category": "NLP",
        "size_mb": 85.4,
        "is_paid": false,
        "price": null,
        "version": "1.0.3",
        "status": "active",
        "avg_rating": 0.0,
        "rating_count": 0,
        "trust_score": 0.0,
        "mostly_used_score": 0.0,
        "date_of_creation": "2025-12-20T10:30:00Z",
        "updated_at": "2025-12-20T10:30:00Z",
        "description": "AI summarization utility"
    },
    {
        "id": 2,
        "app_name": "ChatGPT",
        "category": "NLP",
        "size_mb": 120.5,
        "is_paid": true,
        "price": 20.0,
        "version": "v5.0",
        "status": "active",
        "avg_rating": 4.7,
        "rating_count": 1250000,
        "trust_score": 92.0,
        "mostly_used_score": 95.0,
        "date_of_creation": "2022-11-30T00:00:00Z",
        "updated_at": "2025-12-20T10:30:00Z",
        "description": "Conversational AI assistant for general-purpose tasks"
    },
    {
        "id": 3,
        "app_name": "Gemini",
        "category": "Multimodal AI",
        "size_mb": 115.2,
        "is_paid": true,
        "price": 19.99,
        "version": "v2.0",
        "status": "active",
        "avg_rating": 4.6,
        "rating_count": 540000,
        "trust_score": 90.0,
        "mostly_used_score": 88.0,
        "date_of_creation": "2023-12-06T00:00:00Z",
        "updated_at": "2025-12-20T10:30:00Z",
        "description": "Google's multimodal AI for reasoning, code, and content"
    },
    {
        "id": 4,
        "app_name": "Microsoft Copilot",
        "category": "Productivity",
        "size_mb": 98.8,
        "is_paid": true,
        "price": 30.0,
        "version": "v2025.12",
        "status": "active",
        "avg_rating": 4.5,
        "rating_count": 350000,
        "trust_score": 91.0,
        "mostly_used_score": 89.0,
        "date_of_creation": "2023-03-16T00:00:00Z",
        "updated_at": "2025-12-20T10:30:00Z",
        "description": "AI assistant integrated across Microsoft 365 and web"
    },
    {
        "id": 5,
        "app_name": "Claude",
        "category": "NLP",
        "size_mb": 110.0,
        "is_paid": true,
        "price": 20.0,
        "version": "v3.5",
        "status": "active",
        "avg_rating": 4.6,
        "rating_count": 300000,
        "trust_score": 93.0,
        "mostly_used_score": 86.0,
        "date_of_creation": "2023-03-14T00:00:00Z",
